--   CREATE TABLE IF NOT EXISTS messages (text TEXT, photo TEXT, user TEXT, date TEXT);

CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT, photo TEXT, user TEXT, date TEXT);